<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>burger_control</name>
  <version>0.1.0</version>
  <description>
    Manipulación de Burger-Cell: pick &amp; place de la caja con MoveIt Task Constructor
    sobre el Kinova Gen3 de 6 GDL con pinza Robotiq 2F-85.
  </description>
  <maintainer email="henry.roncancio@unimilitar.edu.co">Henry Roncancio</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>moveit_task_constructor_core</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>tf2_ros</depend>
  <depend>geometry_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>shape_msgs</depend>
  <depend>eigen</depend>

  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>moveit_task_constructor_capabilities</exec_depend>
  <exec_depend>moveit_task_constructor_visualization</exec_depend>
  <exec_depend>kinova_gen3_6dof_robotiq_2f_85_moveit_config</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
